### ISSUE TITLE
Authorization example?

### ISSUE THREAD

**Issue by MattIzSpooky** [graphframework/graphstack#30]
I am quite fond of Vesper but I can't figure out how I should do authorization in this framework because i am quite inexperienced.

Could you extend the advanced example with a simple JWT implementation?

**Comment by kalinichenko88** [comment]
https://github.com/kalinichenko88/vesper-jwt-example – my simple example

enhancements:

1. Add refresh token for generating new access token
2. A checking token may move to `authorizationChecker` from `setupContainer`. A verification token process may be without database query

And other issue #21

**Comment by MattIzSpooky** [comment]
This was exactly what I was looking for, thanks!
