### ISSUE TITLE
[Feature Request] Generate GraphQL automatically

### ISSUE THREAD

**Issue by syabro** [graphframework/graphstack#31]
Is it possible to use typescript introspection or typeorm to generate GraphQL mappings?

**Comment by MichalLytek** [comment]
It's possible in the same way that you can use typescript introspection to generate table schema with typeorm - you need a set of decorators and a couple of manuals inputs (enums, unions, interfaces, scalars and other graphql stuffs).

Right now for Node.js we have two solutions:
- vesper - typeorm centric, automatic resolving, fetching from db, etc. but manual schema using SDL
- [TypeGraphQL](https://github.com/19majkel94/type-graphql) - define schema as classes (just like tables with typeorm classes), no SDL but require some manual work to create generic resolver for CRUD actions and field resolvers for relations fetching from db

Maybe at one time we join our forces with pleerock and create an ultimate solution for this problem :wink

**Comment by syabro** [comment]
@19majkel94 I'll check your project, thanks 👍

**Comment by pleerock** [comment]
> Is it possible to use typescript introspection or typeorm to generate GraphQL mappings?

Currently this is not what vesper is supposed for.

@19majkel94 TypeGraphQL generates schema automatically based on classes, right? Maybe thats what @syabro is looking for.

**Comment by MichalLytek** [comment]
@pleerock yes, you define your schema only with classes and decorators :wink:
@syabro you can have TypeORM and TypeGraphQL [defined in one model class](
https://github.com/19majkel94/type-graphql/blob/master/examples/typeorm-basic-usage/entities/user.ts)

**Comment by pleerock** [comment]
Cool, I think this can be closed since generating graphql is not what vesper currently tries to do. But lets see what future is going to bring us :)
