### ISSUE TITLE
Project outdated?

### ISSUE THREAD

**Issue by kalinichenko88** [graphframework/graphstack#49]
Project is awesome. I used it several times.
But I'm a little confused by what the project looks abandoned. Is have any plans for future versions?

I don't found roadmap or project board.
No contribution guide, not clearly how contribute start.

**Comment by biels** [comment]
I am insterested in knowing if project is still actively maintained as well

**Comment by zhenwenc** [comment]
Try [type-graphql](https://github.com/19majkel94/type-graphql), and/or [@nestjs/graphql](https://github.com/nestjs/graphql).

I am currently using them both, and pretty happy with it.

**Comment by rustamwin** [comment]
@pleerock :slightly_smiling_face:

**Comment by planeight** [comment]
I'm also interested in if this project is still being developed or what? I've noticed the other similar projects @zhenwenc mentioned, but what's up with vesper?

**Comment by planeight** [comment]
What exactly is the difference between vesper and nestjs, and others?

**Comment by yubozhao** [comment]
Hi guys, I am going to start maintain a fork of this project.  First couple things are updating Apollo related projects. @kalinichenko88 @biels 

The fork will be github.com/atalaya-io/vesper

**Comment by biels** [comment]
Cool @yubozhao you could leave a link to the fork here for reference

**Comment by elie222** [comment]
https://github.com/atalaya-io/vesper

Doesn't look like there was progress.

**Comment by kalinichenko88** [comment]
Roadmap could help, but we haven't it

**Comment by yubozhao** [comment]
@elie222 @kalinichenko88 Yes, we haven't updated it.  We didn't touch this layer for a pretty long time.  But if you guys have PR, I will merge it and hopefully soon, we will start contributing to the fork

**Comment by agustif** [comment]
Well, I arrived to Vesper because on typestack @pleerock himself recommends it, I would wait what he has to say.

Maybe he wants to get some extra help to manage all non typeorm projects. But I would love to use the framework he thinks works best, since I'm already using typeorm, class-validators, routing-controllers etc...

This looks neat, but it seems NestJS is the only thing being maintaned by a large enough community in the TS web framework area?
